#!/sbin/openrc-run
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

config_file=${config_file:-/etc/scylla-manager-agent/scylla-manager-agent.yaml}
run_dir=${run_dir:-/run/scylla-manager-agent}

command="/usr/bin/scylla-manager-agent"
command_args=""
command_background="true"
command_progress="true"
pidfile=${run_dir}/${SVCNAME}.pid
user=${USER:-scylla-manager}
group=${GROUP:-scylla-manager}
retry="SIGTERM/120"
start_stop_daemon_args="--user ${user} --group ${group}"

depend() {
    use net localmount logger
}

start_pre() {
    checkpath -d -m 0750 -o "${user}":"${group}" "${run_dir}"
    if [ ! -f ${config_file} ]; then
        eerror "Missing configuration file ${config_file}"
        return 1
    fi
}
