#!/bin/sh

export JAVA_HOME=$(java-config -O)

#FIXME: workaround for HIVE-2757 (NOTE: HADOOP_HOME is obsolete for Hadoop .23)
export HADOOP_HOME=${HADOOP_HOME:-/usr/lib/hadoop}

export HIVE_HOME=/usr/lib/hive
exec /usr/lib/hive/bin/hiveserver2 "$@"
