#!/sbin/runscript
# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

pidfile=${pidfile:-"/run/${SVCNAME}.pid"}

command="/usr/bin/consul"
command_args="agent ${command_args} -pid-file ${pidfile}"
command_background="true"
start_stop_daemon_args="--stdout /var/log/consul/${SVCNAME}.log"

description="tool for service discovery, monitoring and configuration."
extra_started_commands="reload telemetry"

depend() {
	need hostname
	use net
}

stop() {
	# We need to override the default stop function
	# because it uses SIGTERM whereas consul needs a SIGINT
	# to shutdown gracefully
    ebegin "Stopping ${SVCNAME}"
    start-stop-daemon --signal SIGINT --pidfile "${pidfile}"
    eend $?
}

reload() {
	ebegin "Reloading ${SVCNAME}"
	start-stop-daemon --signal SIGHUP --pidfile "${pidfile}"
	eend $?
}

telemetry() {
    ebegin "Logging telemetry for ${SVCNAME}"
    start-stop-daemon --signal SIGUSR1 --pidfile "${pidfile}"
    eend $?
}